### ISSUE TITLE
Use one image folder in Multiple demo content install

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson-Backups-Extension#12]
Hi @moldcraft 

Is it possible to use one image folder in Multiple demo content Install folder ?

Most of the time we use same images for Multiple demo content install. Just database are change according to design style.
From remote demo content install if comes with  array like this. it will save tons of space
```
$cfg = array(
	'files' => array(
		 'defaultslider-inlineform' => array(
                     'db'=>'defaultslider-inlineform/database.json.txt.zip',
                     'file'=> 'f.zip'
                 ),
		 'defaultslider-popupform' => array(
                     'db'=>'defaultslider-popupform/database.json.txt.zip',
                     'file'=> 'f.zip'
                 ),
		 'woo-revoslider' => array(
                     'db'=>'woo-revoslider/database.json.txt.zip',
                     'file'=> 'f.zip'
                 ),
	),
);
```
Also if possible within theme demo bundle folder This also saved theme demo content bundle file size. 

Thanks

**Comment by moldcraft** [comment]
> Most of the time we use same images for Multiple demo content install. Just database are change according to design style.

I don't agree with this. Our theme always has different images (all demos are completely unique).

Your theme demos look the same just the blocks have different arrangement?

----

Sorry, this task is a bit complicated and doesn't seem to help much users which have unique demos (which I think are the majority), so we will not invest time in it.
