### ISSUE TITLE
[Suggestion] Minimum server requirement to install demo content

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson-Backups-Extension#13]
Hi
We have seen lots of server problem to install theme for time out and others issue.

It will be great if backup extension set some limit details. like if this pass minimum requirement to install content no error will display. 
Like max_execution_time, memory_limit, upload_max_filesize

Also upload_max_filesize depand on theme file size. so if we have option. hey our theme file size "20MB"  And if server below file upload size a notice will appear

We can get all the value with ini_get();

Within avada theme have a notice system https://theme-fusion.com/knowledgebase/what-to-do-if-xml-import-fails/

**Comment by moldcraft** [comment]
Hello,

We don't have minimum requirements, it should work on any server. In case of a problem we will inspect it and find the exact cause of the problem.
