### ISSUE TITLE
Disable image restore

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson-Backups-Extension#15]
Hello, 

Is it possible to disable image restore function for specific demos or somehow skip already resized images (if for some demos we use images with resized versions)? Image restore can be annoying slow, therefore we want to create a few demos with improved installation speed.

**Comment by moldcraft** [comment]
The restore happens [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.7/includes/module/tasks/type/class-fw-ext-backups-task-type-image-sizes-restore.php#L59-L62), if you know how to make it skip already existing resizes, please create pull request or give us the solution and we will make the changes.

**Comment by moldcraft** [comment]
I can add a filter [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.7/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L766) and [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.7/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L840) so you will be able to `add_filter()` and disable those tasks.

Will this solution fit your needs?

**Comment by pear1** [comment]
Yes, if we can use this filter for specific demos.

**Comment by moldcraft** [comment]
In the filter you will have access to demo details (like ID)

**Comment by pear1** [comment]
That would be awesome.

**Comment by moldcraft** [comment]
```php
function _filter_theme_fw_backups_do_image_sizes_restore($do, FW_Ext_Backups_Task_Collection $collection) {
	if (
		$collection->get_id() === 'demo-content-install'
		&&
		($task = $collection->get_task('demo:demo-download'))
		&&
		($task_args = $task->get_args())
		&&
	    isset($task_args['demo_id'])
		&&
	    in_array($task_args['demo_id'], array('DEMO_ID_1', 'DEMO_ID_2'))
	) {
		$do = false;
	}
	
	return $do;
}
add_filter(
	'fw:ext:backups:add-restore-task:image-sizes-restore', 
	'_filter_theme_fw_backups_do_image_sizes_restore'.
    10, 2
);
```

**Comment by moldcraft** [comment]
Download latest Backups extension from Github and test the filter. Let us know it works and it will be included in the next release.

**Comment by pear1** [comment]
When we add this filter, then no demo has _Image Sizes Restore_ task.
How can we get demo ID? We tried local folder names, but that didn't work.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/15#issuecomment-212854963

`$task_args['demo_id']`

**Comment by pear1** [comment]
Tried this, but all demos skip Image Sizes Restore task.

```
function _filter_theme_fw_backups_do_image_sizes_restore(
    $do,
    FW_Ext_Backups_Task_Collection $collection
) {
    if (
        $collection->get_id() === 'demo-content-install'
        &&
        ($task = $collection->get_task('demo:demo-download'))
        &&
        ($task_args = $task->get_args())
        &&
        isset($task_args['demo_id'])
        &&
        in_array($task_args['demo_id'], array('demo-local-643e272z588b54db5abf0af67f730345'))
    ) {
        $do = false;
    }

    return $do;
}
add_filter(
    'fw:ext:backups:add-restore-task:image-sizes-restore', 
    '_filter_theme_fw_backups_do_image_sizes_restore'.
    10, 2
);

```

**Comment by moldcraft** [comment]
Debug that code and check why it always enters in `if`.

**Comment by pear1** [comment]
The issue was this:
```
'_filter_theme_fw_backups_do_image_sizes_restore'# **.**
10, 2
```

Now everything works fine, but the _demo_id _ is generated different in every new installation. For example I have demo - Classic and Explore, I need to disable image resize for Classic demo for every client WordPress installation.

**Comment by pear1** [comment]
One way to fix it could be by using demo content folder name instead?

**Comment by moldcraft** [comment]
Yes. The id must be always the same. You are generating random md5 as id?

**Comment by pear1** [comment]
For one of demos I was using value what was given by $task_args['demo_id'], but then I realize that it was dynamically generated.
