### ISSUE TITLE
Multi site usage issues

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson-Backups-Extension#17]
Hello,

There are multiple issues when using multi site, not sure if its meant to be in this way:
1. Install demo content on a _main multi site_ deletes images files and unyson backup files for other multi site (happened once). Looks like issue could be, because the main multi site content are placed just inside uploads not uploads/sites.
2. After install is completed there is no redirection to home page (happened once)
3. Main multi site backup includes other site files

**Comment by moldcraft** [comment]
> 1. Install demo content on a main multi site deletes images files and unyson backup files for other multi site (happened once). Looks like issue could be, because the main multi site content are placed just inside uploads not uploads/sites.

Fixed

> 2. After install is completed there is no redirection to home page (happened once)

It works for me.

> 3. Main multi site backup includes other site files

Fixed

----

Please download latest dev version from github and test the extension.

**Comment by pear1** [comment]
These issues are solved.

Thank you.
