### ISSUE TITLE
Theme Settings goes in to infinite loading

### ISSUE THREAD

**Issue by clusterthemes** [ThemeFuse/Unyson-Backups-Extension#20]
Hi. A client faces a problem. Website works fine, but when it goes to Theme Settings the page goes into infinite load (wp-admin/themes.php?page=fw-settings) 

Other tabs working fine. Latest updates installed.

Do you have any idea what it can be?
Thanks.

**Comment by moldcraft** [comment]
Hello,

Test please with a default WordPress theme: create `framework-customizations/theme/options/settings.php` with a few options. If it will work, then it's a theme problem
