### ISSUE TITLE
Demo Content Install malformed JSON

### ISSUE THREAD

**Issue by JeffreyNaval** [ThemeFuse/Unyson-Backups-Extension#24]
When creating a content backup. database.json.txt have empty lines.
This cause the Demo Content Install to show `Failed to decode line {line_number} from db file. Syntax error, malformed JSON`

**To replicate.**
- Create a new content backup
- Follow [Demos on remote server](http://manual.unyson.io/en/latest/extension/backups/#demos-on-remote-server)
- Proceed to Demo Installation

**Comment by moldcraft** [comment]
Hello,

Can you send me your `database.json.txt` to `moldcraft[at]email.com`?
