### ISSUE TITLE
Demo content install issue

### ISSUE THREAD

**Issue by eyeswizard** [ThemeFuse/Unyson-Backups-Extension#25]
hello guys,
i'm facing this error while i'm trying to install demo content
`Invalid byte position (current: 0, received: 0)`

this is the code i'm using in my functions.php
``` php
add_filter( 'fw:ext:backups-demo:demos', 'window_demo_content' );
function window_demo_content( $demos ) {
	$demos_array = array(
		'news-demo'  => array(
			'title'        => esc_html__( 'News Demo', 'window' ),
			'screenshot'   => 'http://bbioon.com/window/demo/content/news.png',
			'preview_link' => 'http://bbioon.com/window/news'
		),
		'sport-demo' => array(
			'title'        => esc_html__( 'Sport Demo', 'window' ),
			'screenshot'   => 'http://bbioon.com/window/demo/content/sport.png',
			'preview_link' => 'http://bbioon.com/window/sport'
		),
		'blog-demo'  => array(
			'title'        => esc_html__( 'Blog Demo', 'window' ),
			'screenshot'   => 'http://bbioon.com/window/demo/content/blog.png',
			'preview_link' => 'http://bbioon.com/window/blog'
		),
	);

	$download_url = 'http://www.bbioon.com/window/demo_content/';

	foreach ($demos_array as $id => $data) {
		$demo = new FW_Ext_Backups_Demo($id, 'piecemeal', array(
			'url' => $download_url,
			'file_id' => $id,
		));
		$demo->set_title($data['title']);
		$demo->set_screenshot($data['screenshot']);
		$demo->set_preview_link($data['preview_link']);

		$demos[ $demo->get_id() ] = $demo;

		unset($demo);
	}

	return $demos;
}
```

and this is the code i'm using in config.php
```php
$cfg = array(
	'files' => array(
		'news-demo'  => dirname(__FILE__) . '/content/news.zip',
		'sport-demo' => dirname(__FILE__) . '/content/sport.zip',
		'blog-demo'  => dirname(__FILE__) . '/content/blog.zip',
	),
);
```

i can provide you with any login data that you need

**Comment by moldcraft** [comment]
Your download link is 404 http://www.bbioon.com/window/demos/

It should be an empty page with 400 error code, like this

![screenshot from 2016-07-27 11-19-04](https://cloud.githubusercontent.com/assets/1475489/17168607/fe4aaada-53eb-11e6-8084-4c6de846f5a1.png)

**Comment by eyeswizard** [comment]
i moved the url to http://www.bbioon.com/window/demo_content/

it gives me an empty page 
![](http://i.imgur.com/hXGX8b7.png)

what should i do?

**Comment by eyeswizard** [comment]
@moldcraft i need help here

**Comment by eyeswizard** [comment]
this is the error
![](http://i.imgur.com/5emPSiF.png)

**Comment by moldcraft** [comment]
It works http://www.bbioon.com/window/demo_content/?id=news-demo&position=0

Maybe you have antivirus that is blocking requests to your site (if it is on localhost).

If the site is live, can you send me admin/ftp access to `moldcraft[at]email.com`?

**Comment by moldcraft** [comment]
Or you can debug [this script](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/includes/module/tasks/type/download/type/piecemeal/server/index.php) on your sever to check where the execution is not going well.

**Comment by eyeswizard** [comment]
i solved the error `Invalid byte position (current: 0, received: 0)`
i tried to upgrade php version from 5.4 to 5.6 and it worked 

but i'm getting a new error `Zip open failed (code 19). Please try again`

i tried with two different zip files

what is the wrong with this?

**Comment by eyeswizard** [comment]
this is my activated php extensions 

![](http://i.imgur.com/EQnGfYv.png)

**Comment by moldcraft** [comment]
I don't know, I need to inspect your code to find the problem.

**Comment by eyeswizard** [comment]
i sent you an email with the access details.

thank you.

**Comment by moldcraft** [comment]
Thanks, I will take a look in a few hours.

**Comment by moldcraft** [comment]
Hello,

It took me a lot of time to investigate [this issue](https://github.com/ThemeFuse/Unyson/issues/1818#issuecomment-235711685), so I will inspect this issue tomorrow.

**Comment by eyeswizard** [comment]
it still give me the error `Zip open failed (code 19). Please try again`
i tried the theme and files on another server and it gives me the same error.

i also tried another zip files, other host. i can't find the solution.

did you find any solution ? @moldcraft

**Comment by moldcraft** [comment]
Hello,

I was busy with other tasks and forgot about this, sorry.

Error code `19` [means](http://php.net/manual/en/zip.constants.php#83827) `Not a zip archive`

I inspected your server:

1. I downloaded `wp-content/uploads/fw-backup/tmp/piecemeal.zip`.
2. I tried to open it with php

    ```php
	add_action('admin_notices', function(){
		$zip = new ZipArchive();
		fw_print(
			$zip->open(
				fw_fix_path(ABSPATH) 
				.'/wp-content/uploads/fw-backup/tmp/piecemeal.zip'
			)
		);
		$zip->close();
	});
    ```

    and I get the `19` error code on both your server and my localhost.

3. It opens on my PC with Archivator App, but I get [error when I do extract](http://static.md/ea4e236b2eb7c51b1535ec9eb0bab0e8.png).

* Maybe the problem is in [these files](http://static.md/eb5948b131d60e629ec312eddf9e3542.png) which contains corrupted characters in their name.
* One time a similar problem, the problem was in Windows Archivator App, for some reason the archives created with it couldn't be opened in PHP. The solution was to create the archives for demo install with WinRar.

**Comment by eyeswizard** [comment]
do you mean i have to download this archive and decompress it then compress it again with my zip archiver to .zip file ?
or to .rar file? 

as you wrote above i tried to extract the `news.zip` on my server and compressed it again and it gives me the same error `Code 19`.

can you describe the solution you provided for more help?
i'm about uploading the theme to themeforest and i only have to fix this issue to create the demo content for the buyers.


Thank you for your help.

**Comment by moldcraft** [comment]
You need `.zip`.

1. Can you upload to dropbox (or some similar service) your Content Backup zip and send me the download link to `moldcraft[at]email.com`?
2. Have you tried to remove those files with corrupted name from the archive?

**Comment by eyeswizard** [comment]
this is what i did:

1. I downloaded the content zip file.
2. extracted it and compressed it again and uploaded it to the server.
3. The same error again.
-----------------------

i extracted the files on the server and removed 2 files:

    88103  07-26-2016 03:08   f/uploads/2016/07/Window-???-news-logo-1.png
     3709  07-26-2016 03:08   f/uploads/2016/07/Window-???-news-logo.png

as you meant `files with corrupted name` above
and compressed the file again and still give me the error.

i have sent you the download link for the original file (without any edit).

**Comment by eyeswizard** [comment]
Small notice: when i use the same file in the restore backup page  it works correctly, which it means there is no issue with the file but the issue may be with the demo install system.

**Comment by moldcraft** [comment]
Inspecting... Please don't do anything on the server. I will let you know when I am done

**Comment by eyeswizard** [comment]
okay...

**Comment by eyeswizard** [comment]
this is the main demo http://bbioon.com/window/news i can provide you with the access information when you need it.

**Comment by moldcraft** [comment]
I compared the original `news.zip` and the downloaded `piecemeal.zip` and they differ by 3 bytes at the beginning of the file. I am trying to figure out where they come from

**Comment by eyeswizard** [comment]
if you need to create a new demo content zip i can provide you with the admin access on the main demo site.

**Comment by moldcraft** [comment]
1. I added [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/download/type/piecemeal/server/index.php#L117)

    ```php
	file_get_contents('http://requestb.in/...?'. http_build_query(array(
		's' => strlen($data)
	)));
    ```

    and it shows `s=3000000`

2. I added [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L196)

    ```php
		file_get_contents('http://requestb.in/...?'. http_build_query(array(
			's'  => strlen($response['body'])
		)));
    ```

    and it shows `s=3000003`.

    Also to check if the problem maybe is in `wp_remote_get()`, I added [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/download/type/piecemeal/class-fw-ext-backups-task-type-download-piecemeal.php#L127)


    ```php
		file_get_contents('http://requestb.in/...?'. http_build_query(array(
			's' => strlen(file_get_contents(add_query_arg(
				array(
					'id' => urlencode($args['file_id']),
					'position' => $state['position'],
					'size' => $state['piece_size'],
				),
				$args['url']
			)))
		)));
		
		return new WP_Error('t', 'Test');
    ```

    and it also shows `s=3000003`.

So something is adding 3 bytes to server response content.

----

I added here

```php
file_get_contents('http://requestb.in/...?'. http_build_query(array(
	'c' => substr(file_get_contents(add_query_arg(
		array(
			'id' => urlencode($args['file_id']),
			'position' => $state['position'],
			'size' => $state['piece_size'],
		),
		$args['url']
	)), 0, 3)
)));
```

and it shows `cc=%EF%BB%BF`.

[Google shows](https://www.google.com/webhp#q=%25EF%25BB%25BF) that others encountered this problem, and it turns out that this character sequence is related to [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8).

----

I will add a fix that removes those extra bytes.

**Comment by eyeswizard** [comment]
which explains that the same file works correctly in the restore backup page and didn't work with the same file when needs to request it from the server

**Comment by moldcraft** [comment]
The release will be tomorrow https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/241

So better submit your theme tomorrow in the evening when the update will be live and the TF staff will be able to test your theme without encountering this problem.

**Comment by eyeswizard** [comment]
i can wait you, take your time.

thank you for the help.
Best regards...

**Comment by UxLabByNinja** [comment]
@eyeswizard Hi, If

> this Invalid byte position (current: 0, received: 0)

is your error so just check the your config.php file for proper linking your zip file.  **'news-demo'  => dirname(__FILE__) . '/content/news.zip',** this is your content link so try to change "/content" to "content" no need to add "/" if your download script in "demo_content" folder. By the way, I got the same problem in my theme solved the problem by changing the path.

**Comment by andreiglingeanu** [comment]
@moldcraft Nice one!

**Comment by nobingit** [comment]
> The release will be tomorrow [ThemeFuse/Unyson-Extensions-Approval#241](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/241)
> 
> So better submit your theme tomorrow in the evening when the update will be live and the TF staff will be able to test your theme without encountering this problem.

hello i am new in unyson i want to implement demo import can you help me to do this?

**Comment by DevWael** [comment]
Hi @nobingit 
Unyson framework is a great framework, but it's now discontinued project, I would suggest you to get another framework like [carbonfields.net](https://carbonfields.net).

Hope it will be back to live again one day.

Regards.

**Comment by nobingit** [comment]
Thank you su much
