### ISSUE TITLE
Unable to locate demo install directory inside theme 

### ISSUE THREAD

**Issue by ashraf92** [ThemeFuse/Unyson-Backups-Extension#26]
I have placed demo content inside admin folder in theme . I have this code done so far

```
function _filter_theme_fw_ext_backups_demo_dirs($dirs) {
       $dirs['/admin/demo-content'] = get_template_directory_uri() . '/admin/demo-content';
        return $dirs;
   }
  add_filter('fw_ext_backups_demo_dirs', '_filter_theme_fw_ext_backups_demo_dirs');
```

But I can not demo import submenu. I guess I wrote wrong directory

**Comment by moldcraft** [comment]
Please inspect [this code](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/extensions/backups-demo/class-fw-extension-backups-demo.php#L129) and figure out what you did wrong

**Comment by ashraf92** [comment]
Got it , Thanks
