### ISSUE TITLE
[Feature request] Add the ability to send schedule backup archives to the configured FTP server

### ISSUE THREAD

**Issue by player0k** [ThemeFuse/Unyson-Backups-Extension#28]

**Comment by moldcraft** [comment]
How will you upload a large file (100+ Mb) via FTP if php timeout is 30 seconds?

**Comment by player0k** [comment]
Good question, but I have not an idea. Some how it needed to separate to small part. [small script which  create zip archives by file limits](https://gist.github.com/jonmaim/1141513)

**Comment by moldcraft** [comment]
It is not a problem to separate the zip, it is a problem how to glue the uploaded pieces together via FTP.

**Comment by player0k** [comment]
Just leave them separated in the backup_timestamp directory.

**Comment by moldcraft** [comment]
@player0k So how a simple user will do restore from such backup?

**Comment by player0k** [comment]
By multi-upload form in the backups extension

**Comment by moldcraft** [comment]
It will be confusing and complicated for users.
