### ISSUE TITLE
Content Backup Issue

### ISSUE THREAD

**Issue by Paulskr** [ThemeFuse/Unyson-Backups-Extension#29]
Hello guys. Demo content back up will not save some images format like png when im (Create Content Backup Now).
Otherwise (Create Full Backup Now) its does. Thx

**Comment by moldcraft** [comment]
[This task](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/3df146519af25b5784a0c85395c66c9957f81e2a/includes/module/tasks/type/class-fw-ext-backups-task-type-image-sizes-remove.php#L71-L101) removes image sizes to make the Demo Content (Demo Install) zip smaller.

Can you give more details about which images are removed and why you decided that it is a bug?
