### ISSUE TITLE
Unyson Backup Extension Issue.

### ISSUE THREAD

**Issue by aamirs332** [ThemeFuse/Unyson-Backups-Extension#3]
Hello, I found an issue in backup extension. When i update extension and create a  demo install. it creates backup, but when i click on download link then an error page displayed. This issue is in new update version of backup extension.

Please have a look on JPEG.
![bk1](https://cloud.githubusercontent.com/assets/5873187/11365742/5f3b4c02-92ca-11e5-9d51-d839720ca50d.jpg)

When I click on Download Link
![bk2](https://cloud.githubusercontent.com/assets/5873187/11365758/756a65da-92ca-11e5-913a-a86e94d1d1be.jpg)

Please help me. i am waiting your kind response.

Regards,

**Comment by moldcraft** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

**Comment by azharijelek** [comment]
Hi @moldcraft , What's your recommendation for post revision cleaner plugin?

**Comment by moldcraft** [comment]
https://wordpress.org/plugins/better-delete-revision/

**Comment by azharijelek** [comment]
Thank you :+1:

**Comment by aamirs332** [comment]
Hi @moldcraft, I need your a little bit help, I create following folder structure in my theme "my-theme/demo-content/clinic/"
and then paste manifest.php file in it. having code in it

$manifest = array();
$manifest['title'] = __('One Page Demo', 'fw');
$manifest['screenshot'] = get_template_directory_uri(). '/demo-content/images/screenshot.jpg';
$manifest['preview_link'] = 'http//fashioner.themographics.com/fashioner-v1/';

after that i create a Create Demo Install and after downloading it, i extract it in "my-theme/demo-content/clinic/" but nothing heppened. Please help me. if i am wrong way.

**Comment by moldcraft** [comment]
It should work based on what you explained.

* Add [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/10e1b79139ef575f83fa1d7ff8341f019de60830/extensions/backups-demo/class-fw-extension-backups-demo.php#L141) `fw_print($dirs);` (or debug the `get_demos()` method to find why your demo is not detected)
* If you are not on Windos, check if your directory is readable by others. (has chmod `755` not `700`)

**Comment by aamirs332** [comment]
Hi @moldcraft , hope you are doing good. i just need your help, please have a look on screen shot which is showing my demo folder structure. please if you can give me demo how to create a demo for my clients in my theme. 

![screenshot_1](https://cloud.githubusercontent.com/assets/5873187/11389402/25225914-9362-11e5-8917-fdc8e61c73c7.jpg)

Thanks :)

**Comment by aamirs332** [comment]
When i download new extension from live through plugin available extensions. its totally different extension which is at GitHub. i think that is the main reason. but after downloading new backup extension from git and paste it in plugin extension folder then error occurs, while my plugin and extension up to date.

![screenshot_2](https://cloud.githubusercontent.com/assets/5873187/11390017/a6ee9912-9367-11e5-8da3-1b0703b044c4.jpg)

![screenshot_3](https://cloud.githubusercontent.com/assets/5873187/11390021/aed0cdee-9367-11e5-87ed-16ef4a97783b.jpg)

![screenshot_4](https://cloud.githubusercontent.com/assets/5873187/11390024/b2d68668-9367-11e5-813c-f7122b5176ee.jpg)

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/3#issuecomment-159498698

You put the entire theme in `{theme}/demo-content/`

Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/index.html#create-demos)

> https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/3#issuecomment-159509024

Backup extension is "Compatible with your current theme". I told you here https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/3#issuecomment-159243546

> Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`

----

New backup extension is called "Backup & Demo Content" and there is `auto-install/` directory (please delete it)

**Comment by aamirs332** [comment]
Thanks.
