### ISSUE TITLE
[Urgent] Duplicate entry Backup content

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson-Backups-Extension#34]
Hi @moldcraft ! I'm not sure if it's the problem with new Backup version.
But today many clients report this problem when install demo content
 

> Failed to insert row from line 2323 into table _fwbk_wp_options. Duplicate entry 'theme_mods_topseo' for key 'option_name'

Do you have any ideas?

Thanks!

**Comment by duongancol** [comment]
I downgrade to version 2.0.15 and it worked

**Comment by duongancol** [comment]
So maybe the problem comes from the change in version 2.0.16

**Comment by moldcraft** [comment]
@duongancol Please send me the admin and ftp credentials to `moldcraft[at]email.com`

**Comment by duongancol** [comment]
I sent, please check it!

**Comment by moldcraft** [comment]
Inspecting...

**Comment by moldcraft** [comment]
The fix https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/9563796ab270b3b345152bcee2b95bd58a9fcb21#diff-3c5fc3af6c96cc923c455995d18fbb25R754

If you can't wait until we will release a new version of the Backup extension, you can edit your demo install `database.json.txt` and remove the line `1912`

```
...:{"option_id":"282","option_name":"theme_mods_topseo",...
```

**Comment by duongancol** [comment]
What exactly to delete in this line? 
`{"type":"row","data":{"table":"options","row":{"option_id":"282","option_name":"theme_mods_topseo2","option_value":"a:16:{i:0;b:0;s:18:\"nav_menu_locations\";a:2:{s:9:\"secondary\";i:14;s:7:\"primary\";i:30;}s:12:\"c_pattern_bg\";`

When I delete 

`:{"option_id":"282","option_name":"theme_mods_topseo"`

it showed syntax error

**Comment by duongancol** [comment]
so there're any problems with demo content if we delete that line? 
If yes, it's helpful as you can release Backup extension now because I got bad rating yesterday because of this problem.

**Comment by moldcraft** [comment]
> When I delete
>
> `:{"option_id":"282","option_name":"theme_mods_topseo",`
>
> it showed syntax error

Delete the entire line. I showed you a piece of that line to be able to identify it.

**Comment by moldcraft** [comment]
Have you ever tested new extensions releases on [Extensions Approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/295)?

**Comment by moldcraft** [comment]
> so there're any problems with demo content if we delete that line? 

The explanation is here https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/9563796ab270b3b345152bcee2b95bd58a9fcb21#diff-3c5fc3af6c96cc923c455995d18fbb25R754

**Comment by duongancol** [comment]
The new version works well
