### ISSUE TITLE
cannot close zip file

### ISSUE THREAD

**Issue by bert677** [ThemeFuse/Unyson-Backups-Extension#35]
Hi,

I am trying to install demo content for one of my sites but keep getting a error
"cannot close zip file"

here is the log from the debug.log file.

PHP Warning:  ZipArchive::close(): Internal error in /usr/www/users/lifehftqbn/wp-content/plugins/unyson/framework/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-zip.php on line 107

Please help... I have no idea why this is happening... I have installed this content on other site without issues.

Thanks
B

**Comment by moldcraft** [comment]
Hello,

1. Are you able to create Content Backups from the Backup page? How big is the zip?
2. Can you send me your admin and ftp credentials to `moldcraft[at]email.com`?

**Comment by bert677** [comment]
Hi,

It was a database issue… I deleted and recreated and problem was solved.
Thanks
