### ISSUE TITLE
Maximum execution time of 29 seconds exceeded in ...

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson-Backups-Extension#39]
Hello,

Lot of my clients have this issue: _Maximum execution time of 29 seconds exceeded..._
Most of them helps solution by increasing max execution time and max input time.
Can you include something like this in this extension execution time?

```
@ini_set( 'max_execution_time', '200000' );
@ini_set( 'max_input_time ', '200000' );
```

Thank you

**Comment by moldcraft** [comment]
1. https://github.com/ThemeFuse/Unyson-Backups-Extension/compare/v2.0.18...v2.0.19#diff-cf235647150056d7682c3db517c39485R70
2. https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/335
