### ISSUE TITLE
Not working with built in PHP server

### ISSUE THREAD

**Issue by andreiglingeanu** [ThemeFuse/Unyson-Backups-Extension#4]
I'm mainly using for quick testing the built-in PHP server: `php -S localhost:3000` and everything worked fine, besides your implementation of this extension.

Maybe you know an easy fix, besides using Apache or Nginx?

**Comment by moldcraft** [comment]
Please give us the errors from error log.

**Comment by andreiglingeanu** [comment]
It gives me the `Operation timed out after 5005 milliseconds with 0 bytes received` error. After restarting the server it actually starts working but the error is not disappearing.

If I'm trying to download a bigger file (90mb) the error [pops up](https://www.dropbox.com/s/z775l1uqxwev0up/Screenshot%202015-11-25%2016.54.04.png?dl=0) after downloading the first ~5mb.

**Comment by moldcraft** [comment]
Sorry, I never used built-in server and in production it is never used. So I don't want to waste time with this issue (we have a lot of issues waiting to be fixed). You can try to debug the code yourself to find the problem and submit a pull request.

P.S. I can't see your screenshots, it shows [this](https://static.md/991719d1ca901e75e8a5db609b6f663e.png) already a few minutes.

**Comment by andreiglingeanu** [comment]
Okay. Let's close this issue for now.

Screenshots already uploaded.

**Comment by moldcraft** [comment]
About [this screenshot](https://www.dropbox.com/s/z775l1uqxwev0up/Screenshot%202015-11-25%2016.54.04.png?dl=0) your internet connection was slow and the script was unable to download 1MB in 23 seconds.

It works this way:
* Download 3MB in 23 seconds (30 - 7. 7 is some time for later script execution to not cause the entire script timeout)
* If the download fails, download 2MB in 23 seconds.
* If the download fails, download 1MB in 23 seconds.
* If the download fails, display the error.

**Comment by andreiglingeanu** [comment]
Yep, tried again with better connection - worked well.

Thanks.
