### ISSUE TITLE
Backup + Demo Content Issues

### ISSUE THREAD

**Issue by ajmartin12** [ThemeFuse/Unyson-Backups-Extension#40]
I am trying to move across the wordpress site from my local to the clients server. 

With reference to http://manual.unyson.io/en/latest/extension/backups/#demos-bundled-in-theme I've tried the following:

**Demos bundled in theme**
I am getting the error: 

> Failed to create tmp table _fwbk_wp_pmxi_files

**Demos on remote server**
> Invalid byte position (current: 0, received: 0)

The remote server is returning a 200 status request. 

What is the best solution to move the content to the client's server? I am focused on Demos bundled in theme at the moment

**Comment by moldcraft** [comment]
> Demos bundled in theme
>
> Failed to create tmp table _fwbk_wp_pmxi_files

Maybe your client's server does not support some mysql encoding available on your local server.
Try to find the error message with more details on client's hosting error.log.
Or inspect on your localhost the mysql table `wp_pmxi_files` to detect if it has some special settings/encoding.
Or edit `database.json.txt` in demo install and remove every line related to `pmxi_files` (to skip this table).
