### ISSUE TITLE
Demo content install menu hide on tools

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson-Backups-Extension#42]
### Backup Extension Active. 
![](https://puu.sh/u3MBZ/94d9cca3f6.png)

### But no demo content menu there 
![](https://puu.sh/u3MEp/2e2749e55c.png)

### But I see a notice in top Zip extensions need to be installed 

![](https://puu.sh/u3MHQ/f933ed231f.png)

### If you have more than one notice user most of the time not followed this notice. 

![](https://puu.sh/u3NcY/825fba1cbc.png)

It will be better user will go to Tools-> Demo content installs page.  And hide all the demo content. And show a note with more details. 

> Ops Unyson Backup requires PHP zip extension.  If you are not familiar with PHP Zip extension, please contact your hosting provider. Or something else

Hide the installation menu not a good solution.  Last two days we received three tickets about this issue. 

Or please give us hook to modify our self. 

Thanks

**Comment by moldcraft** [comment]
I changed the message to

> Oops, Unyson Backup requires PHP Zip module but it is not enabled on your server. If you are not familiar with PHP Zip module, please contact your hosting provider.

Is it ok?

**Comment by Ataurr** [comment]
It looks like still, Menu hides from Tools menu. 
![](https://puu.sh/u8AZe/9e3b47405f.png)


Send user to **Tools-> Demo content install** page. And hide all demo contents And a show a notice there.  That will be more accurate I think. 

Hide the Demo content menu still will be the pain for support stuff. Always tell the user to check any notice showing like this or not. Or login to check why the menu is not showing and inform the user to install Zip extension.

**Comment by moldcraft** [comment]
@Ataurr I did that

https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/343 The release will be on Monday

**Comment by Ataurr** [comment]
### Ahh just found another server same issue and tested. 
![](https://puu.sh/u9Mwj/adfeec9a86.png)

### Should we highlight the error ?
![](https://puu.sh/u9MXi/fbf46b2e74.png)
