### ISSUE TITLE
Database export: Execution stopped when timeout 0

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson-Backups-Extension#5]
Hi there, 

I'm trying to use the Demo Content import feature, which seems awesome since the last update. 
However, whenever I push the "Create Content Backup Now" button... It try to export the Database and it fails everytime. I've tried on 3 different networks. 

```15 mins ago Database export: Execution stopped (next step did not started)```

![backup_ _woffice_dev_ _wordpress](https://cloud.githubusercontent.com/assets/5446124/11587377/2c85ec3e-9a79-11e5-98dd-2a805ecd5ec8.jpg)

Any idea ?

**Comment by moldcraft** [comment]
Can you check error.log ?

**Comment by 2Fwebd** [comment]
I've checked the debug.log and indeed that was an issue in our database table ... 
It didn't stopped since 40 minutes so I guess that'll work out that time ;)

I keep you updated

**Comment by moldcraft** [comment]
Can you share what exactly is the problem in database?

**Comment by 2Fwebd** [comment]
Still the same issue and all the logs are empty :/ 

It was an issue with a table creation SQL query from one of the extension. But even when the error is gone, it's not working. 

Any idea ? Let me know if you need anything.

**Comment by moldcraft** [comment]
I have no idea, only an error, but you say the error log shows nothing.

I need access to your site and code (`moldcraft[at]email.com`), or a way to reproduce the problem on my side.

**Comment by 2Fwebd** [comment]
Sent ;)

**Comment by moldcraft** [comment]
I added [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/fc720a09e5e6da97adc64f60fae70a6d36869c01/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L279)

```php
. ((int)ini_get('max_execution_time'))
// or: . self::backups()->get_timeout()
```

and it shows

![](https://static.md/075b963edcdaba64fd0850e4526cc6e8.png)

I think that 0 is the problem *(haven't tested and can't say for sure)*.

Where do you have `set_time_limit(0)` and why it was set/needed?

**Comment by 2Fwebd** [comment]
Thanks for the digging, absolutely no idea ....Where can I check that ?

**Comment by moldcraft** [comment]
In my PhpStorm IDE I can search in all files, but via FTP I can't do that.
Try to zip the entire project from cPanel file manager, download the zip, extract it and use an IDE to search in all files for `set_time_limit` string.

**Comment by 2Fwebd** [comment]
Ok, I'll do that, I keep you updated ;)

**Comment by 2Fwebd** [comment]
Hi there, 

You're right, the issue was the set_time_limit(0)

It's in both Woocommerce & Learndash. I deactivated both plugins and it's working just fine ;)

**Comment by moldcraft** [comment]
TODO: Handle cases when timeout is set to `0` (display warning or treat that case in code)

**Comment by 2Fwebd** [comment]
Actually, it works just fine with Woocommerce. So it's caused by the set_time_limit(0) from Learndash plugin.

**Comment by praveenrchauhan** [comment]
I also faced the same issue while installing the demo content. After reading the above threads, it seems some conflict because of the time limit. Even in my case, I have LearnDash plugin installed. So, I just deactivated it, installed demo content and then reactivated. By this way it worked.

@moldcraft , can a fix or hook (to allow code tweak) be added from your end in this backup extension, so that one can do some changes for the time limit to get rid of this issue at least for time being (unless you figure out a proper solution)?

**Comment by moldcraft** [comment]
I'll just add a fix soon, no need for hooks.

**Comment by praveenrchauhan** [comment]
That sounds good.

**Comment by Eynsteyn** [comment]
Hi, i have still the same issue

I added `. ((int)ini_get('max_execution_time'))` in a file \wp-content\plugins\unyson\framework\extensions\backups\includes\module\tasks\class--fw-ext-backups-module-tasks.php

![screenshot](https://cloud.githubusercontent.com/assets/7722113/15177412/8fbd24da-1778-11e6-8f7d-5c4144a75fe5.png)

error.log is empty
Any ideas?

**Comment by moldcraft** [comment]
> error.log is empty

Maybe your error.log is not working (like on most hostings). Try to [this](http://sourcebox.io/8b8c68d8abcbf4b13f5197c13142d38a/php) to get some error messages.

**Comment by Eynsteyn** [comment]
I meant that in error.log file was no error file related to this issue.

**Comment by moldcraft** [comment]
Can you give me admin/ftp access to your site? If yes, send the details to `moldcraft[at]email.com`

**Comment by Eynsteyn** [comment]
I copied the whole site and the database itself on the local server, and the error was gone.
Import and Export work again.
The problem in our server.
Thanks
