### ISSUE TITLE
Disable donations

### ISSUE THREAD

**Issue by maartenhetworks** [ThemeFuse/Unyson-Backups-Extension#54]
How can I disable donations and buy tickets option?

**Comment by ViorelEremia** [comment]
What "donations" ?
You mean this [plugin](https://wordpress.org/plugins/give/)

**Comment by maartenhetworks** [comment]
This part: http://prntscr.com/i0nizh

**Comment by ViorelEremia** [comment]
What theme do you use?
Unyson dosen't have these options by default?

**Comment by maartenhetworks** [comment]
This theme: https://themeforest.net/item/church-wordpress-theme-holy-cross-church-wp/19530898

**Comment by ViorelEremia** [comment]
here is unyson support but these options come from theme or another plugin. 
Please contact theme developer.

**Comment by maartenhetworks** [comment]
Thanks
