### ISSUE TITLE
Can we do flush rewrite rules on demo content installation complete?

### ISSUE THREAD

**Issue by yura-x** [ThemeFuse/Unyson-Backups-Extension#55]
Hello! 
After demo content installation we have to manually go to Settings -> Permalinks and click on 'Save' button because our custom post types permalinks are broken and causes 404 error.
Does Backup Extension has any actions on demo content installation complete? We could not find it in documentation or in extension code.
Thank you!

**Comment by yura-x** [comment]
Does this code will be correct resolving?
`
function _action_flush_rewrite_rules() {
 flush_rewrite_rules();
}
add_action( 'fw:ext:backups:restore', '_action_flush_rewrite_rules' );
`

**Comment by ViorelEremia** [comment]
Can you test with that commit?
