### ISSUE TITLE
Errors while the Demo Install 

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson-Backups-Extension#6]
Hi there, 

So I've been playing quite a lot with this new extension and it looks awesome ! You've done an awesome job ! :) 

I just have a few issues that I can't understand :

1. Sometime, I see this error : 
**Invalid source dir**

So, after some researches in the extension's files, it seems that this arg is empty/missing : $args['source_dir']

Any idea how I can fix that ? Or maybe I've missed something. 

2. One of our 3 demos, I got this issue : 
**Timed out**

With this in the log : 
```[09-Dec-2015 08:52:40 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /.../woffice/framework-customizations/extensions/backups/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php on line 549```

It's only for one demo, and I have no idea why ... 

Please let me know if you need any extra detail. Here is the code in our hooks.php file : 

```
function woffice_filter_theme_fw_ext_backups_demos($demos) {
    $demos_array = array(
        'business-demo' => array(
            'title' => __('Business Demo', 'woffice'),
            'screenshot' => 'https://woffice.io/demos/demo-business.png',
            'preview_link' => 'http://alka-web.com/woffice-business/',
        ),
        'community-demo' => array(
            'title' => __('Community Demo', 'woffice'),
            'screenshot' => 'https://woffice.io/demos/demo-community.png',
            'preview_link' => 'https://woffice.io/demo-community/',
        ),
        'school-demo' => array(
            'title' => __('School Demo', 'woffice'),
            'screenshot' => 'https://woffice.io/demos/demo-school.png',
            'preview_link' => 'http://alka-web.com/woffice-school/',
        ),
    );

    $download_url = 'https://woffice.io/demos/index.php';

    foreach ($demos_array as $id => $data) {
        $demo = new FW_Ext_Backups_Demo($id, 'piecemeal', array(
            'url' => $download_url,
            'file_id' => $id,
        ));
        $demo->set_title($data['title']);
        $demo->set_screenshot($data['screenshot']);
        $demo->set_preview_link($data['preview_link']);

        $demos[ $demo->get_id() ] = $demo;

        unset($demo);
    }

    return $demos;
}
add_filter('fw:ext:backups-demo:demos', 'woffice_filter_theme_fw_ext_backups_demos');
// We don't save the Theme version used / exported 
function woffice_filter_fw_ext_backups_db_restore_keep_options($options, $is_full) {
    if (!$is_full) {
        $options[ 'template' ] = true;
        $options[ 'stylesheet' ] = true;
    }

    return $options;
}
add_filter('fw_ext_backups_db_restore_keep_options', 'woffice_filter_fw_ext_backups_db_restore_keep_options', 10, 2);
````

Thank you, 

2F

**Comment by 2Fwebd** [comment]
Let me know if you need any access (I've sent some of them last week about the other issue). Or anything I can do to help you fix it.

**Comment by moldcraft** [comment]
Send me plase admin/ftp details to `moldcraft[at]email.com`, the steps to reproduce the problems and I will take a look when will have time (today or tomorrow)

**Comment by 2Fwebd** [comment]
Hi molcraft, 

Sent. Let me know if you need anything else. Feel free to make any change on this install.

**Comment by 2Fwebd** [comment]
It might be something related to the cache.. 

Whenever I click the install button, it goes from 3MB to 27MB whereas I have a REALLY bad internet connection. 

It's the same for the 3 demos. 

Hope that helps

**Comment by moldcraft** [comment]
> Sometime, I see this error : Invalid source dir

Actually it happens always (with first demo).

The problem: Your zip contains

```
demo-name/
    database.json.txt
    f/
        uploads/
```

it must contain

```
database.json.txt
f/
    uploads/
```

**Comment by moldcraft** [comment]
On demo install, in database is set the active theme used when the demo was created. Your theme is called `woffice` (directory name). The third demo fails, because when it was created, the active theme was `woffice-1-5-1` (directory name), but that directory doesn't exist on current installation. So after database restore (after active theme was restored/set to `woffice-1-5-1`), on next step/request, the site is down because it can't activate not existing theme.

![](https://static.md/de9933f4b561c62c836b3c1af2e53bfc.png)

**Comment by moldcraft** [comment]
> One of our 3 demos, I got this issue : Timed out

I didn't see that error. Please fix the above problems, and if the timeout will still happen, let me know and I will inspect the code again.

**Comment by moldcraft** [comment]
> Whenever I click the install button, it goes from 3MB to 27MB whereas I have a REALLY bad internet connection.

Your internet connection doesn't matter, the download happens on server side.

The download works this way:

```
Download 3MB...OK ---next-request---> Download 3MB...OK ---next-request---> ...
```

that happens without delay, the internal requests are executed in chain.

On the other side, your browser makes every 3 seconds a request to check current installation status, so between 3 secons, on server side, happens many chained request. I see that [alka-web.com](http://www.dnswatch.info/dns/dnslookup?la=en&host=www.alka-web.com&type=A&submit=Resolve) and [woffice.io](http://www.dnswatch.info/dns/dnslookup?la=en&host=woffice.io&type=A&submit=Resolve) are on the same server, so the download should work very fast.

**Comment by 2Fwebd** [comment]
Hi @moldcraft !

Thanks for all the details .. and sorry for these stupid issues & php errors, I was making some other tests on my side.. I've cleaned up all zip and it looks awesome !! Good job again for this amazing extension.

**Comment by 2Fwebd** [comment]
And @moldcraft, I'm sorry I didn't had the time to work on the documentation for our extensions and the Github reps. I'm know it's not perfect coding (as I'm not a back-end developer but they work). But here are the extensions we're using available for any Unyson theme developer who want to use some of them as inspiration or whatever : https://woffice.io/extensions/ I will write some documentation but I can't know. If anyone as any question, just get in touch at contact[at]alka-web.com
(I'll try to update theme regularly as we're making A LOT of changes everyday).

**Comment by 2Fwebd** [comment]
Everything is working except the Business one : 
![demo_content_install_ _woffice_dev_ _wordpress](https://cloud.githubusercontent.com/assets/5446124/11722833/6bfe234e-9f6b-11e5-9187-48873ac1de45.jpg)

Do you need the .zip file ?

**Comment by moldcraft** [comment]
I will log in again later, test and try to find the problem.

**Comment by moldcraft** [comment]
> Do you need the .zip file ?

If you mean the theme zip, yes please (send it to `moldcraft[at]email.com`). It will be more convenient for me to test on my local machine (where I can check error.log)

**Comment by moldcraft** [comment]
No need for zip, I already created with this script (and downloaded it)

```php
add_action('init', function(){
	if (!isset($_GET['test'])) {
		return;
	}

	$dir = fw_fix_path(get_template_directory());
	$zip_path = fw_fix_path(WP_CONTENT_DIR) .'/uploads/theme.zip';

	$zip = new ZipArchive();
	$zip->open($zip_path, ZipArchive::CREATE);

	$files = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($dir),
		RecursiveIteratorIterator::LEAVES_ONLY
	);

	foreach ($files as $name => $file) {
		if (!$file->isDir()) { // Skip directories (they would be added automatically)
			if (($file_path = $file->getRealPath()) !== $zip_path) {
				$zip->addFile(
					$file_path,
					substr(fw_fix_path($file_path), strlen($dir) + 1) // relative
				);
			}
		}
	}

	$zip->close();

	fw_print('OK');
});
```

**Comment by moldcraft** [comment]
I reproduced the "Timed out" on my localhost. Investigating...

**Comment by moldcraft** [comment]
The timeout happens [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.2/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L545). There we did a hack to prevent mysql error on very big string insert (mysql max allowed packet reached).

Instead of one 

```sql
INSERT INTO {table} (...) VALUES ('very_big_string ...')
```

we do 

```sql
INSERT INTO {table} (...) VALUES ('very_big_string_part_1')
UPDATE {table} SET x = CONCAT(x, 'very_big_string_part_2') WHERE ...
UPDATE {table} SET x = CONCAT(x, 'very_big_string_part_3') WHERE ...
```

----

Inspecting...

**Comment by moldcraft** [comment]
In `database.json.txt` was a row with one column value ending with slash

![](https://static.md/d21a02ba1c9b0127c90f75fcc5c2bf21.png)

which caused infinite execution in [this loop](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.2/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L545-L552).

----

P.S. I get [notices in footer](https://static.md/c7a0c2ce5bf970fa056868e5df15d223.png)

```
Notice: Undefined offset: 1 in /var/www/wordpress/public_html/wp-content/themes/woffice/framework-customizations/extensions/woffice-map/class-fw-extension-woffice-map.php on line 275

Notice: Trying to get property of non-object in /var/www/wordpress/public_html/wp-content/themes/woffice/framework-customizations/extensions/woffice-map/class-fw-extension-woffice-map.php on line 157
```

**Comment by moldcraft** [comment]
I will create an Extension Release Approval today.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/163

If you need, I can release it tomorrow, just let me know.

**Comment by 2Fwebd** [comment]
Hello @moldcraft, 

Firstly, impressive job !!! Sorry for the delay on that, I'm just back. I've just made the change in the business-demo.zip file and it works well. 

Also, thanks for all the details on the issue. I'll take care of the PHP errors on my side tonight ;)

If I can do anything to help you on Unyson or whatever, just let me know. 

Just about the **backups** extension ? for now it hasn't replaced the **backup** extension in the extensions library right ? Because, I've added the extension directly in themes/framework-customizations/ but doesn't seem to be a perfect solution regarding the extension's coming updates. 

What do you think ?

**Comment by 2Fwebd** [comment]
No hurry on our side as I've edited the zip file directly, it's working fine for now ;)

**Comment by moldcraft** [comment]
> I've just made the change in the business-demo.zip file and it works well.

No need to change that manually, the problem was in our script, I just explained why.

> Just about the backups extension ? for now it hasn't replaced the backup extension in the extensions library right

Yes, it will not be replaced if you put it there. But you will get fatal error if the extension is installed in Unyson (that happened on my side)

**Comment by 2Fwebd** [comment]
Thanks for the details @moldcraft, I know but for now that'll do the trick ;)

Thanks again,

**Comment by macthecoder** [comment]
I also having the problem installing demo content from Server it shows: "Invalid source dir: C:/xampp/htdocs/faded/wp-content/uploads/fw-backup/tmp/f"
http://prntscr.com/hjbrzo --This error. 
I have no idea how to solve this error.
