### ISSUE TITLE
Exclude image sizes from content backup and recreate them on restore, to make the demo install zip smaller

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson-Backups-Extension#8]
When an image is uploaded, it is multiplied based on registered sizes with [add_image_size](https://developer.wordpress.org/reference/functions/add_image_size/).

Our main theme demo at the moment is 90MB, we deleted the sizes manually and the zip size was decreased down to 13MB.

**Comment by moldcraft** [comment]
Please test. [Download](https://github.com/ThemeFuse/Unyson-Backups-Extension/archive/master.zip) and extract in `unyson/framework/extensions/backups`

**Comment by azharijelek** [comment]
Hi @moldcraft , today I just tried to use the latest backups extension. 

The result I've got is:

1. Creating Content-only backups. and then the zip still contains multiplied images (by <code>add_image_size() </code>)

2. Tried Installing demo from the zip file above, the popup message shows "removing image sizes". <- I don't know what exactly it means.

3. Demo install finish. The desired resized-images ( add_image_size() )  are disappeared. Not copied to upload folder. At this point, I'm still wondering why those images don't get copied into uploads directory.

I guess this issue related to "recreate" function.

Thank you.

**Comment by moldcraft** [comment]
Can't reproduce https://vid.me/vLbK

----

Can you give me admin/ftp access to your site?

**Comment by azharijelek** [comment]
Hi moldcraft, I'm sorry I wasn't clear enough.

But I was actually talking about demo installer with remote server. 

I've recorded a video too. I will upload it later and put the link here

**Comment by moldcraft** [comment]
Content restore and demo install is the same thing.

**Comment by azharijelek** [comment]
Just uploaded the video. https://vid.me/S4NH

here's the new case: I've disabled any unnecessary plugins (wp retina 2x, regenerate thumbnails, etc). 
I've cleaned up the database too to remove transients, draft, and revisions. Only want to make sure that the database won't be bloated.

But still.
Create content backup -> upload to remote server -> install my theme on different domain -> Demo install success -> image thumbnails aren't reproduced, only the original ones.

I tried to use [ v2.0.2](https://github.com/ThemeFuse/Unyson-Backups-Extension/releases/tag/v2.0.2) and it works well.

Is there any hook or filter that I can use to disable removing resized images?

thank you.

**Comment by azharijelek** [comment]
Okay. Seems like I have to do a **Restore** task after installing demo content. 

I'm sure the demo installer only done the job in "restore database" state.

The **recreate** image task seems only in **Restore** task.

**Comment by azharijelek** [comment]
I've found out the problem.

Here's the file we need to edit:
`unyson/framework/extensions/backups/extensions/backups-demo`

at line 411. we can see this code:
<pre>
$collection->add_task(new FW_Ext_Backups_Task(
	$id_prefix .'db-restore',
	'db-restore',
	array(
		'dir' => $tmp_dir,
		'full' => $full,
	))
);
</pre>

So I've added the code below right after db-restore state. 
<pre>
if (!$full) {
	$collection->add_task(new FW_Ext_Backups_Task(
		$id_prefix .'image-sizes-restore',
		'image-sizes-restore',
		array()
	));
}
</pre>

**Comment by moldcraft** [comment]
The code is [there](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.5/includes/module/tasks/class--fw-ext-backups-module-tasks.php#L853) are you sure you have [the latest version](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.5/manifest.php#L13)?

Also maybe there are errors in apache error.log?

**Comment by azharijelek** [comment]
Yeah, but not in [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/master/extensions/backups-demo/class-fw-extension-backups-demo.php#L417)

I'm sure I have downloaded the latest version

**Comment by moldcraft** [comment]
Omg, what a fail :facepalm:

To prevent such cases, please [follow this repository](https://github.com/ThemeFuse/Unyson-Extensions-Approval) in order to test new extension versions before they are going to be released.
